project_id = "ubekgmqoqheqaqihnowl"

[functions.paypal-payment]
verify_jwt = false

[functions.auth-register]
verify_jwt = false

[functions.auth-reset-pin]
verify_jwt = false

[functions.auth-change-pin]
verify_jwt = false
